version: '2'
services:
  app:
    container_name: lets-eat-app
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    env_file:
      - .env
    command: yarn start:dev
    volumes:
      - .:/letseat/app
    restart: always
    ports:
      - "9090:9090"
    mem_limit: 300m
