export const CUSTOMER_LOGIN_REQUEST = '@@customer/LOGIN_REQUEST';
export const CUSTOMER_LOGIN_REQUEST_FAILED = '@@customer/LOGIN_REQUEST_FAILED';

export const CUSTOMER_REGISTRATION_REQUEST = '@@customer/REGISTRATION_REQUEST';
export const CUSTOMER_REGISTRATION_REQUEST_FAILED = '@@customer/REGISTRATION_REQUEST_FAILED';

export const CUSTOMER_REGISTRATION_OR_LOGIN_REQUEST_SUCCEEDED =
	'@@customer/REGISTRATION_OR_LOGIN_REQUEST_SUCCEEDED';

export const CUSTOMER_FETCH_PROFILE_REQUEST = '@@customer/FETCH_PROFILE_REQUEST';
export const CUSTOMER_FETCH_PROFILE_REQUEST_SUCCEEDED =
	'@@customer/FETCH_PROFILE_REQUEST_SUCCEEDED';
export const CUSTOMER_FETCH_PROFILE_REQUEST_FAILED = '@@customer/FETCH_PROFILE_REQUEST_FAILED';

export const INITIALIZE_CLIENT_STATE = '@@INITIALIZE_CLIENT_STATE';
